# Generated by Django 3.1.13 on 2022-06-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_administrativo', '0041_pacientetratamientoasignado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PacienteTratamientoAsignado',
        ),
    ]
