# Generated by Django 3.1.13 on 2022-06-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tratamiento', '0004_auto_20220523_1511'),
        ('gestion_administrativo', '0043_pacientetratamientoasignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tratamientos',
            field=models.ManyToManyField(through='gestion_administrativo.PacienteTratamientoAsignado', to='gestion_tratamiento.Tratamiento'),
        ),
    ]
